spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.yandex.ru
    username: il.sach@yandex.ru
    password: ildar1357
    port: 465
    protocol: smtps

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION


recaptcha:
  secret: 6LeMp6MUAAAAAFP-xwRCNN71DYZwCKg74G4HwUSb

mail:
  debug: false

upload:
  path: /home/dev/uploads


server:
  port: 9000

hostname: localhost:${server.port}




