spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.yandex.ru
    username: uw@dru.su
    password: 12345678
    port: 465
    protocol: smtps

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION


recaptcha:
  secret: 6LduQVoUAAAAACpkNtp9c5WWgyGENzIxZqF9SbZL




